# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcsg325-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Mostafa/Desktop/computer arc/LEC_Project/FULL_CODE/Lec_Project.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Mostafa/Desktop/computer arc/LEC_Project/FULL_CODE/Lec_Project.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/Mostafa/Desktop/computer arc/LEC_Project/FULL_CODE/Lec_Project.srcs/sources_1/new/Write_to_reg_Mux.v}
  {C:/Users/Mostafa/Desktop/computer arc/LEC_Project/FULL_CODE/Lec_Project.srcs/sources_1/new/Sign_Extend.v}
  {C:/Users/Mostafa/Desktop/computer arc/LEC_Project/FULL_CODE/Lec_Project.srcs/sources_1/new/Reg_out_R.v}
  {C:/Users/Mostafa/Desktop/computer arc/LEC_Project/FULL_CODE/Lec_Project.srcs/sources_1/new/Register_File.v}
  {C:/Users/Mostafa/Desktop/computer arc/LEC_Project/FULL_CODE/Lec_Project.srcs/sources_1/new/Read_1_OR_3_Mux.v}
  {C:/Users/Mostafa/Desktop/computer arc/LEC_Project/FULL_CODE/Lec_Project.srcs/sources_1/new/PC_Mux.v}
  {C:/Users/Mostafa/Desktop/computer arc/LEC_Project/FULL_CODE/Lec_Project.srcs/sources_1/new/PC.v}
  {C:/Users/Mostafa/Desktop/computer arc/LEC_Project/FULL_CODE/Lec_Project.srcs/sources_1/new/Instruction_Register.v}
  {C:/Users/Mostafa/Desktop/computer arc/LEC_Project/FULL_CODE/Lec_Project.srcs/sources_1/new/Instruction_Memory.v}
  {C:/Users/Mostafa/Desktop/computer arc/LEC_Project/FULL_CODE/Lec_Project.srcs/sources_1/new/Data_Memory_Reg.v}
  {C:/Users/Mostafa/Desktop/computer arc/LEC_Project/FULL_CODE/Lec_Project.srcs/sources_1/new/Data_Memory.v}
  {C:/Users/Mostafa/Desktop/computer arc/LEC_Project/FULL_CODE/Lec_Project.srcs/sources_1/new/Control_Unit.v}
  {C:/Users/Mostafa/Desktop/computer arc/LEC_Project/FULL_CODE/Lec_Project.srcs/sources_1/new/ALU_reg.v}
  {C:/Users/Mostafa/Desktop/computer arc/LEC_Project/FULL_CODE/Lec_Project.srcs/sources_1/new/ALU_B_Mux.v}
  {C:/Users/Mostafa/Desktop/computer arc/LEC_Project/FULL_CODE/Lec_Project.srcs/sources_1/new/ALU_A_Mux.v}
  {C:/Users/Mostafa/Desktop/computer arc/LEC_Project/FULL_CODE/Lec_Project.srcs/sources_1/new/ALU.v}
  {C:/Users/Mostafa/Desktop/computer arc/LEC_Project/FULL_CODE/Lec_Project.srcs/sources_1/new/DataPath.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top DataPath -part xc7a35tcsg325-2L


write_checkpoint -force -noxdef DataPath.dcp

catch { report_utilization -file DataPath_utilization_synth.rpt -pb DataPath_utilization_synth.pb }
